goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.Uri', 'goog.object', 'goog.math.Integer', 'goog.string.StringBuffer', 'goog.array', 'goog.math.Long']);
goog.addDependency("../process/env.js", ['process.env'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../cljs/tools/reader/impl/utils.js", ['cljs.tools.reader.impl.utils'], ['goog.string', 'cljs.core', 'clojure.string']);
goog.addDependency("../cljs/tools/reader/reader_types.js", ['cljs.tools.reader.reader_types'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer', 'cljs.tools.reader.impl.utils']);
goog.addDependency("../cljs/tools/reader/impl/inspect.js", ['cljs.tools.reader.impl.inspect'], ['cljs.core']);
goog.addDependency("../cljs/tools/reader/impl/errors.js", ['cljs.tools.reader.impl.errors'], ['cljs.core', 'cljs.tools.reader.reader_types', 'cljs.tools.reader.impl.inspect', 'clojure.string']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core', 'cljs.core.async.impl.buffers', 'goog.async.nextTick']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/pprint.js", ['cljs.pprint'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer', 'clojure.string']);
goog.addDependency("../cljs/tools/reader/impl/commons.js", ['cljs.tools.reader.impl.commons'], ['cljs.tools.reader.impl.errors', 'cljs.core', 'cljs.tools.reader.reader_types', 'cljs.tools.reader.impl.utils']);
goog.addDependency("../cljs/tools/reader.js", ['cljs.tools.reader'], ['cljs.tools.reader.impl.commons', 'goog.string', 'cljs.tools.reader.impl.errors', 'cljs.core', 'cljs.tools.reader.reader_types', 'goog.string.StringBuffer', 'cljs.tools.reader.impl.utils', 'goog.array']);
goog.addDependency("../cljs/tools/reader/edn.js", ['cljs.tools.reader.edn'], ['cljs.tools.reader.impl.commons', 'cljs.tools.reader', 'goog.string', 'cljs.tools.reader.impl.errors', 'cljs.core', 'cljs.tools.reader.reader_types', 'goog.string.StringBuffer', 'cljs.tools.reader.impl.utils']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['cljs.tools.reader.edn', 'cljs.tools.reader', 'cljs.core', 'goog.object', 'goog.string.StringBuffer']);
goog.addDependency("../figwheel/client/utils.js", ['figwheel.client.utils'], ['goog.userAgent.product', 'goog.string', 'cljs.core', 'goog.object', 'goog.string.StringBuffer', 'cljs.pprint', 'goog.async.Deferred', 'clojure.string', 'cljs.reader']);
goog.addDependency("../figwheel/client/socket.js", ['figwheel.client.socket'], ['cljs.core', 'goog.object', 'figwheel.client.utils', 'cljs.reader']);
goog.addDependency("../cljs/spec/gen/alpha.js", ['cljs.spec.gen.alpha'], ['goog.Uri', 'cljs.core']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.timers']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../figwheel/client/file_reloading.js", ['figwheel.client.file_reloading'], ['goog.string', 'goog.net.jsloader', 'goog.Uri', 'cljs.core', 'goog.object', 'cljs.core.async', 'clojure.set', 'goog.html.legacyconversions', 'figwheel.client.utils', 'goog.async.Deferred', 'clojure.string']);
goog.addDependency("../figwheel/client/heads_up.js", ['figwheel.client.heads_up'], ['goog.dom', 'goog.string', 'cljs.core', 'goog.dom.dataset', 'goog.object', 'cljs.core.async', 'cljs.pprint', 'figwheel.client.utils', 'figwheel.client.socket', 'clojure.string']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../cljs/spec/alpha.js", ['cljs.spec.alpha'], ['cljs.core', 'goog.object', 'clojure.string', 'clojure.walk', 'cljs.spec.gen.alpha']);
goog.addDependency("../cljs/repl.js", ['cljs.repl'], ['goog.string', 'cljs.core', 'goog.string.format', 'cljs.spec.alpha']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['goog.userAgent.product', 'goog.Uri', 'cljs.core', 'goog.object', 'cljs.core.async', 'figwheel.client.file_reloading', 'figwheel.client.utils', 'cljs.repl', 'figwheel.client.heads_up', 'figwheel.client.socket', 'clojure.string', 'cljs.reader']);
goog.addDependency("../figwheel/connect.js", ['figwheel.connect'], ['cljs.core', 'figwheel.client']);
goog.addDependency("../cljsjs/p5/development/p5.inc.js", ['cljsjs.p5'], [], {'foreign-lib': true});
goog.addDependency("../quil/middlewares/deprecated_options.js", ['quil.middlewares.deprecated_options'], ['cljs.core']);
goog.addDependency("../quil/util.js", ['quil.util'], ['cljs.core', 'clojure.string']);
goog.addDependency("../quil/sketch.js", ['quil.sketch'], ['goog.dom', 'cljs.core', 'quil.middlewares.deprecated_options', 'goog.object', 'goog.events.EventType', 'goog.style', 'goog.events', 'quil.util']);
goog.addDependency("../quil/core.js", ['quil.core'], ['cljsjs.p5', 'quil.sketch', 'cljs.core', 'clojure.string', 'quil.util']);
goog.addDependency("../pucks/globals.js", ['pucks.globals'], ['cljs.core']);
goog.addDependency("../pucks/vec2D.js", ['pucks.vec2D'], ['cljs.core', 'quil.core', 'pucks.globals']);
goog.addDependency("../pucks/util.js", ['pucks.util'], ['cljs.core', 'pucks.vec2D', 'quil.core', 'cljs.repl', 'pucks.globals']);
goog.addDependency("../pucks/agents/generic.js", ['pucks.agents.generic'], ['cljs.core', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/agents/active.js", ['pucks.agents.active'], ['pucks.agents.generic', 'cljs.core', 'quil.core', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world17.js", ['pucks.worlds.dev.world17'], ['cljs.core', 'pucks.agents.active']);
goog.addDependency("../pucks/agents/chest.js", ['pucks.agents.chest'], ['pucks.agents.generic', 'cljs.core', 'quil.core', 'pucks.globals']);
goog.addDependency("../pucks/agents/shooter.js", ['pucks.agents.shooter'], ['cljs.core', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/agents/stone.js", ['pucks.agents.stone'], ['pucks.agents.generic', 'cljs.core', 'quil.core']);
goog.addDependency("../pucks/agents/nursery.js", ['pucks.agents.nursery'], ['pucks.agents.generic', 'cljs.core', 'quil.core', 'pucks.globals']);
goog.addDependency("../pucks/agents/vent.js", ['pucks.agents.vent'], ['pucks.agents.generic', 'cljs.core', 'quil.core']);
goog.addDependency("../pucks/worlds/dev/world23.js", ['pucks.worlds.dev.world23'], ['pucks.agents.shooter', 'cljs.core', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent']);
goog.addDependency("../pucks/agents/mapdonor.js", ['pucks.agents.mapdonor'], ['cljs.core', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/agents/swarmevolver.js", ['pucks.agents.swarmevolver'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/agents/gate.js", ['pucks.agents.gate'], ['pucks.agents.generic', 'cljs.core', 'pucks.vec2D', 'quil.core', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/agents/zapper.js", ['pucks.agents.zapper'], ['pucks.agents.generic', 'cljs.core', 'quil.core']);
goog.addDependency("../pucks/agents/user.js", ['pucks.agents.user'], ['cljs.core', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/agents/donor.js", ['pucks.agents.donor'], ['cljs.core', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/worlds/ai/world8.js", ['pucks.worlds.ai.world8'], ['pucks.agents.mapdonor', 'pucks.agents.shooter', 'cljs.core', 'pucks.agents.gate', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user', 'pucks.agents.donor']);
goog.addDependency("../pucks/agents/beacon.js", ['pucks.agents.beacon'], ['pucks.agents.generic', 'cljs.core', 'quil.core', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world16.js", ['pucks.worlds.dev.world16'], ['pucks.agents.mapdonor', 'pucks.agents.beacon', 'cljs.core', 'pucks.vec2D', 'pucks.agents.vent', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/agents/darter.js", ['pucks.agents.darter'], ['cljs.core', 'pucks.vec2D', 'quil.core', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/agents/startstop.js", ['pucks.agents.startstop'], ['cljs.core', 'pucks.vec2D', 'pucks.agents.active']);
goog.addDependency("../pucks/agents/zigzag.js", ['pucks.agents.zigzag'], ['cljs.core', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world3.js", ['pucks.worlds.dev.world3'], ['pucks.agents.startstop', 'cljs.core', 'pucks.agents.zigzag']);
goog.addDependency("../pucks/agents/opener.js", ['pucks.agents.opener'], ['cljs.core', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/worlds/ai/world2.js", ['pucks.worlds.ai.world2'], ['cljs.core', 'pucks.agents.stone', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user', 'pucks.globals']);
goog.addDependency("../pucks/agents/swarmer.js", ['pucks.agents.swarmer'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/agents/linear.js", ['pucks.agents.linear'], ['cljs.core', 'pucks.util', 'pucks.agents.active']);
goog.addDependency("../pucks/worlds/dev/world12.js", ['pucks.worlds.dev.world12'], ['pucks.agents.swarmer', 'pucks.agents.startstop', 'pucks.agents.beacon', 'cljs.core', 'pucks.agents.linear', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.zigzag']);
goog.addDependency("../pucks/worlds/dev/world5.js", ['pucks.worlds.dev.world5'], ['pucks.agents.startstop', 'cljs.core', 'pucks.agents.zigzag']);
goog.addDependency("../pucks/worlds/dev/world19.js", ['pucks.worlds.dev.world19'], ['cljs.core', 'pucks.agents.nursery', 'pucks.vec2D', 'pucks.agents.vent', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/agents/spanner.js", ['pucks.agents.spanner'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world1.js", ['pucks.worlds.dev.world1'], ['pucks.agents.swarmer', 'pucks.agents.beacon', 'pucks.agents.shooter', 'cljs.core', 'pucks.agents.linear', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper']);
goog.addDependency("../pucks/worlds/dev/world22.js", ['pucks.worlds.dev.world22'], ['pucks.agents.spanner', 'cljs.core', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent']);
goog.addDependency("../pucks/worlds/dev/world7.js", ['pucks.worlds.dev.world7'], ['pucks.agents.opener', 'cljs.core', 'pucks.agents.gate', 'pucks.agents.stone', 'pucks.agents.vent', 'pucks.agents.chest', 'pucks.globals']);
goog.addDependency("../pucks/agents/torpedo.js", ['pucks.agents.torpedo'], ['cljs.core', 'pucks.agents.zapper', 'pucks.util']);
goog.addDependency("../pucks/physics.js", ['pucks.physics'], ['cljs.core', 'pucks.vec2D', 'pucks.agents.torpedo', 'quil.core', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/reap.js", ['pucks.reap'], ['cljs.core', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world6.js", ['pucks.worlds.dev.world6'], ['pucks.agents.swarmer', 'pucks.agents.startstop', 'pucks.agents.beacon', 'cljs.core', 'pucks.agents.linear', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.zigzag']);
goog.addDependency("../pucks/worlds/dev/world8.js", ['pucks.worlds.dev.world8'], ['cljs.core', 'pucks.agents.linear', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world13.js", ['pucks.worlds.dev.world13'], ['pucks.agents.swarmer', 'pucks.agents.beacon', 'cljs.core', 'pucks.agents.linear', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.zigzag']);
goog.addDependency("../pucks/agents/spawner.js", ['pucks.agents.spawner'], ['cljs.core', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world14.js", ['pucks.worlds.dev.world14'], ['pucks.agents.spawner', 'cljs.core', 'pucks.agents.nursery', 'pucks.agents.vent']);
goog.addDependency("../pucks/worlds/dev/world18.js", ['pucks.worlds.dev.world18'], ['pucks.agents.swarmer', 'cljs.core', 'pucks.agents.nursery']);
goog.addDependency("../pucks/agents/bondevolver.js", ['pucks.agents.bondevolver'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.agents.active', 'pucks.globals']);
goog.addDependency("../pucks/sensors.js", ['pucks.sensors'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world9.js", ['pucks.worlds.dev.world9'], ['pucks.agents.beacon', 'pucks.agents.shooter', 'cljs.core', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper']);
goog.addDependency("../pucks/neighbors.js", ['pucks.neighbors'], ['cljs.core', 'pucks.vec2D', 'pucks.util', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world10.js", ['pucks.worlds.dev.world10'], ['pucks.agents.beacon', 'cljs.core', 'pucks.agents.darter', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper']);
goog.addDependency("../pucks/worlds/ai/world5.js", ['pucks.worlds.ai.world5'], ['pucks.agents.beacon', 'cljs.core', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user']);
goog.addDependency("../pucks/worlds/ai/world6.js", ['pucks.worlds.ai.world6'], ['pucks.agents.beacon', 'cljs.core', 'pucks.agents.gate', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user', 'pucks.agents.donor']);
goog.addDependency("../pucks/worlds/dev/world2.js", ['pucks.worlds.dev.world2'], ['cljs.core', 'pucks.agents.linear', 'pucks.agents.vent', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world15.js", ['pucks.worlds.dev.world15'], ['cljs.core', 'pucks.agents.swarmevolver', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper']);
goog.addDependency("../pucks/worlds/dev/world4.js", ['pucks.worlds.dev.world4'], ['cljs.core', 'pucks.agents.linear', 'pucks.agents.stone', 'pucks.globals']);
goog.addDependency("../pucks/worlds/ai/world4.js", ['pucks.worlds.ai.world4'], ['pucks.agents.beacon', 'cljs.core', 'pucks.agents.gate', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user', 'pucks.agents.chest']);
goog.addDependency("../pucks/worlds/ai/world7.js", ['pucks.worlds.ai.world7'], ['pucks.agents.shooter', 'cljs.core', 'pucks.agents.gate', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user', 'pucks.agents.donor']);
goog.addDependency("../pucks/worlds/ai/world1.js", ['pucks.worlds.ai.world1'], ['cljs.core', 'pucks.agents.stone', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user']);
goog.addDependency("../pucks/worlds/dev/world20.js", ['pucks.worlds.dev.world20'], ['cljs.core', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.bondevolver']);
goog.addDependency("../pucks/worlds/dev/world21.js", ['pucks.worlds.dev.world21'], ['pucks.agents.spanner', 'cljs.core', 'pucks.agents.nursery', 'pucks.agents.vent']);
goog.addDependency("../pucks/worlds/ai/world3.js", ['pucks.worlds.ai.world3'], ['pucks.agents.beacon', 'cljs.core', 'pucks.agents.stone', 'pucks.agents.nursery', 'pucks.agents.vent', 'pucks.agents.zapper', 'pucks.agents.user']);
goog.addDependency("../pucks/draw.js", ['pucks.draw'], ['cljs.core', 'pucks.vec2D', 'quil.core', 'pucks.globals']);
goog.addDependency("../pucks/worlds/dev/world11.js", ['pucks.worlds.dev.world11'], ['cljs.core', 'pucks.agents.linear', 'pucks.agents.donor', 'pucks.globals']);
goog.addDependency("../pucks/core.js", ['pucks.core'], ['pucks.worlds.dev.world4', 'pucks.physics', 'pucks.worlds.dev.world10', 'cljs.core', 'pucks.worlds.dev.world9', 'pucks.worlds.dev.world7', 'pucks.worlds.dev.world5', 'pucks.sensors', 'pucks.worlds.dev.world6', 'pucks.neighbors', 'pucks.worlds.dev.world2', 'pucks.worlds.dev.world3', 'quil.core', 'pucks.worlds.dev.world8', 'pucks.draw', 'pucks.reap', 'pucks.worlds.dev.world1', 'pucks.globals']);
